version: "3.9"

networks:
  p2b-network-1:
    driver: bridge  # Using bridge instead of overlay for local development

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - /home/ubuntu/public/nginx.conf:/etc/nginx/conf.d/default.conf
      - nginx_logs:/var/log/nginx  # Store logs from NGINX
    ports:
      - "80:80"  # Expose port 80 to the outside world
    networks:
      - p2b-network-1
    depends_on:
      - nodejs-app
    restart: always

  mongo:
    container_name: mongo
    image: mongo:4.4  # Use the official MongoDB image
    ports:
      - "27017:27017"  # Expose MongoDB port
    networks:
      - p2b-network-1
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data

  nodejs-app:
    container_name: nodejs-app
    build:
      context: /home/ubuntu/public  # Local path to the app directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Expose port 3000 (Node.js app)
    env_file:
      - /home/ubuntu/public/.env  # Use the app-specific .env file
    volumes:
      - nodejs_logs:/usr/src/app/logs  # Logs directory
    depends_on:
      - mongo
    networks:
      - p2b-network-1
    restart: always

volumes:
  nodejs_logs:
  nginx_logs:
  mongo_data:
