version: "3.9"

networks:
  p2b-network-1:
    driver: overlay  # Overlay network for Docker Swarm (supports multi-node clusters)

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - /home/ubuntu/public/nginx.conf:/etc/nginx/conf.d/default.conf
      - nginx_logs:/var/log/nginx  # Store logs from NGINX
    ports:
      - "80:80"  # Expose port 80 to the outside world
    networks:
      - p2b-network-1
    depends_on:
      - nodejs-app
    deploy:
      replicas: 2  # Multiple replicas of NGINX for load balancing
      restart_policy:
        condition: any  # Always restart the container if it stops unexpectedly
    restart: always

  mongo:
    container_name: mongo
    image: mongo:4.4  # Use the official MongoDB image
    ports:
      - "27017:27017"  # Expose MongoDB port
    networks:
      - p2b-network-1
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data
    deploy:
      replicas: 1  # One replica of MongoDB (usually you need more for high availability)
      restart_policy:
        condition: any
    restart: always

  nodejs-app:
    container_name: nodejs-app
    build:
      context: /home/ubuntu/public  # Local path to the app directory
      dockerfile: Dockerfile  # Path to the Dockerfile
    ports:
      - "3000:3000"  # Expose port 3000 (Node.js app)
    env_file:
      - /home/ubuntu/public/.env  # Use the app-specific .env file
    volumes:
      - nodejs_logs:/usr/src/app/logs  # Logs directory
    depends_on:
      - mongo
    networks:
      - p2b-network-1
    deploy:
      replicas: 3  # Run 3 instances of the Node.js app for high availability and load balancing
      restart_policy:
        condition: any
    restart: always

volumes:
  nodejs_logs:
  nginx_logs:
  mongo_data:
