version: "3.9"

networks:
  p2b-network-1:
    name: p2b-network-1

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/public:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - nginx_logs:/var/log/nginx  # Store logs from NGINX
    ports:
      - "80:80"  # Expose port 80
    networks:
      - p2b-network-1
    deploy:
      mode: global
    restart: always

  mongo:
    container_name: mongo
    image: mongo:4.4  # Use the official MongoDB image
    ports:
      - "27017:27017"  # Expose MongoDB port
    networks:
      - p2b-network-1
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data

  nodejs-app:
    container_name: nodejs-app
    build:
      context: ./app  # Points to the app directory
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"  # Use PORT from the .env file
    env_file:
      - ./app/.env         # Use the app-specific .env file
    volumes:
      - nodejs_logs:/app/logs  # Logs directory
    depends_on:
      - mongo
    networks:
      - p2b-network-1
    restart: always

volumes:
  nodejs_logs:
  nginx_logs:
  mongo_data:
